// <auto-generated />
using System;
using BookLAB.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BookLAB.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(BookLABDbContext))]
    [Migration("20260405165533_AddCampusCode")]
    partial class AddCampusCode
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BookLAB.Domain.Entities.Attendance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AttendanceStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("CheckInMethod")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTimeOffset?>("CheckInTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("CheckOutTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ScheduleId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AttendanceStatus");

                    b.HasIndex("ScheduleId");

                    b.HasIndex("UserId");

                    b.HasIndex("ScheduleId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("UQ_Attendance_Booking_User");

                    b.ToTable("Attendances", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("15151515-1515-1515-1515-151515151515"),
                            AttendanceStatus = "NotYet",
                            CheckInMethod = "FaceId",
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("11111111-1111-1111-1111-111111111111"),
                            ScheduleId = new Guid("27272727-2727-2727-2727-272727272727"),
                            UserId = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            Id = new Guid("16161616-1616-1616-1616-161616161616"),
                            AttendanceStatus = "NotYet",
                            CheckInMethod = "QR",
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 1, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("22222222-2222-2222-2222-222222222222"),
                            ScheduleId = new Guid("28282828-2828-2828-2828-282828282828"),
                            UserId = new Guid("33333333-3333-3333-3333-333333333333")
                        },
                        new
                        {
                            Id = new Guid("17171717-1717-1717-1717-171717171717"),
                            AttendanceStatus = "NotYet",
                            CheckInMethod = "Manual",
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 1, 18, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("33333333-3333-3333-3333-333333333333"),
                            ScheduleId = new Guid("29292929-2929-2929-2929-292929292929"),
                            UserId = new Guid("11111111-1111-1111-1111-111111111111")
                        });
                });

            modelBuilder.Entity("BookLAB.Domain.Entities.Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BookingStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("BookingType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LabRoomId")
                        .HasColumnType("integer");

                    b.Property<int>("PurposeTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Recur")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<Guid?>("ScheduleId")
                        .HasColumnType("uuid");

                    b.Property<int?>("SlotTypeId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("StudentCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BookingStatus");

                    b.HasIndex("PurposeTypeId");

                    b.HasIndex("ScheduleId");

                    b.HasIndex("SlotTypeId");

                    b.HasIndex("LabRoomId", "StartTime", "EndTime")
                        .HasDatabaseName("IX_Booking_Room_Time");

                    b.ToTable("Bookings", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            BookingStatus = "PendingApproval",
                            BookingType = "Standard",
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("11111111-1111-1111-1111-111111111111"),
                            EndTime = new DateTimeOffset(new DateTime(2025, 2, 1, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            LabRoomId = 1,
                            PurposeTypeId = 1,
                            Reason = "Intro lecture",
                            Recur = 0,
                            SlotTypeId = 1,
                            StartTime = new DateTimeOffset(new DateTime(2025, 2, 1, 8, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            StudentCount = 10
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            BookingStatus = "PendingApproval",
                            BookingType = "Standard",
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 1, 11, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("22222222-2222-2222-2222-222222222222"),
                            EndTime = new DateTimeOffset(new DateTime(2025, 2, 2, 15, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            LabRoomId = 2,
                            PurposeTypeId = 2,
                            Reason = "Practical session",
                            Recur = 0,
                            SlotTypeId = 2,
                            StartTime = new DateTimeOffset(new DateTime(2025, 2, 2, 13, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            StudentCount = 20
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666666"),
                            BookingStatus = "Approved",
                            BookingType = "Standard",
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("33333333-3333-3333-3333-333333333333"),
                            EndTime = new DateTimeOffset(new DateTime(2025, 2, 3, 10, 30, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            LabRoomId = 3,
                            PurposeTypeId = 3,
                            Reason = "Workshop",
                            Recur = 0,
                            SlotTypeId = 3,
                            StartTime = new DateTimeOffset(new DateTime(2025, 2, 3, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            StudentCount = 10
                        });
                });

            modelBuilder.Entity("BookLAB.Domain.Entities.BookingGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("GroupId")
                        .HasDatabaseName("IX_BookingGroup_GroupId");

                    b.HasIndex("BookingId", "GroupId")
                        .IsUnique()
                        .HasDatabaseName("UQ_Booking_Group");

                    b.ToTable("BookingGroups", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777777"),
                            BookingId = new Guid("44444444-4444-4444-4444-444444444444"),
                            GroupId = new Guid("18181818-1818-1818-1818-181818181818")
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-888888888888"),
                            BookingId = new Guid("55555555-5555-5555-5555-555555555555"),
                            GroupId = new Guid("19191919-1919-1919-1919-191919191919")
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-999999999999"),
                            BookingId = new Guid("66666666-6666-6666-6666-666666666666"),
                            GroupId = new Guid("20202020-2020-2020-2020-202020202020")
                        });
                });

            modelBuilder.Entity("BookLAB.Domain.Entities.BookingRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uuid");

                    b.Property<string>("BookingRequestStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RequestedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("ResponseContext")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid?>("ResponsedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.HasIndex("BookingRequestStatus");

                    b.HasIndex("RequestedByUserId");

                    b.HasIndex("ResponsedByUserId")
                        .HasFilter("\"ResponsedByUserId\" IS NOT NULL");

                    b.ToTable("BookingRequests", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("12121212-1212-1212-1212-121212121212"),
                            BookingId = new Guid("44444444-4444-4444-4444-444444444444"),
                            BookingRequestStatus = "Pending",
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 1, 13, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("11111111-1111-1111-1111-111111111111"),
                            RequestedByUserId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("13131313-1313-1313-1313-131313131313"),
                            BookingId = new Guid("55555555-5555-5555-5555-555555555555"),
                            BookingRequestStatus = "Pending",
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("22222222-2222-2222-2222-222222222222"),
                            RequestedByUserId = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            Id = new Guid("14141414-1414-1414-1414-141414141414"),
                            BookingId = new Guid("66666666-6666-6666-6666-666666666666"),
                            BookingRequestStatus = "Pending",
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("33333333-3333-3333-3333-333333333333"),
                            RequestedByUserId = new Guid("33333333-3333-3333-3333-333333333333")
                        });
                });

            modelBuilder.Entity("BookLAB.Domain.Entities.Building", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BuildingImageUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("BuildingName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("CampusId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("CampusId");

                    b.HasIndex("CampusId", "BuildingName")
                        .IsUnique()
                        .HasDatabaseName("UQ_Building_Campus_Name");

                    b.ToTable("Buildings", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BuildingImageUrl = "",
                            BuildingName = "Science Building",
                            CampusId = 1,
                            Description = "Science faculty building"
                        },
                        new
                        {
                            Id = 2,
                            BuildingImageUrl = "",
                            BuildingName = "Engineering Building",
                            CampusId = 1,
                            Description = "Engineering labs"
                        },
                        new
                        {
                            Id = 3,
                            BuildingImageUrl = "",
                            BuildingName = "Admin Building",
                            CampusId = 2,
                            Description = "Administration"
                        });
                });

            modelBuilder.Entity("BookLAB.Domain.Entities.Campus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("CampusCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("CampusImageUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("CampusName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.HasKey("Id");

                    b.HasIndex("CampusName")
                        .IsUnique()
                        .HasDatabaseName("UQ_Campus_Name");

                    b.HasIndex("IsActive");

                    b.ToTable("Campuses", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "1 University Ave",
                            CampusName = "Main Campus",
                            IsActive = true
                        },
                        new
                        {
                            Id = 2,
                            Address = "100 North St",
                            CampusName = "North Campus",
                            IsActive = true
                        },
                        new
                        {
                            Id = 3,
                            Address = "50 West Blvd",
                            CampusName = "West Campus",
                            IsActive = true
                        });
                });

            modelBuilder.Entity("BookLAB.Domain.Entities.EmailTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.ToTable("EmailTemplates", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "<h1>Booking Confirmed</h1>",
                            Type = "0"
                        },
                        new
                        {
                            Id = 2,
                            Content = "<h1>Booking Rejected</h1>",
                            Type = "0"
                        },
                        new
                        {
                            Id = 3,
                            Content = "<h1>Attendance Report</h1>",
                            Type = "0"
                        });
                });

            modelBuilder.Entity("BookLAB.Domain.Entities.Group", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("GroupName");

                    b.HasIndex("OwnerId");

                    b.HasIndex("OwnerId", "GroupName", "IsDeleted")
                        .IsUnique()
                        .HasDatabaseName("UQ_Group_Owner_Name_Active")
                        .HasFilter("\"IsDeleted\" = false");

                    b.ToTable("Groups", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("18181818-1818-1818-1818-181818181818"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("11111111-1111-1111-1111-111111111111"),
                            GroupName = "Team Alpha",
                            IsDeleted = false,
                            OwnerId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("19191919-1919-1919-1919-191919191919"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("22222222-2222-2222-2222-222222222222"),
                            GroupName = "Team Beta",
                            IsDeleted = false,
                            OwnerId = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            Id = new Guid("20202020-2020-2020-2020-202020202020"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("33333333-3333-3333-3333-333333333333"),
                            GroupName = "Team Gamma",
                            IsDeleted = false,
                            OwnerId = new Guid("33333333-3333-3333-3333-333333333333")
                        });
                });

            modelBuilder.Entity("BookLAB.Domain.Entities.GroupMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<string>("SubjectCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("GroupId")
                        .HasDatabaseName("IX_GroupMember_GroupId");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_GroupMember_UserId");

                    b.HasIndex("GroupId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("UQ_Group_User_Member");

                    b.ToTable("GroupMembers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("36363636-3636-3636-3636-363636363636"),
                            GroupId = new Guid("18181818-1818-1818-1818-181818181818"),
                            SubjectCode = "",
                            UserId = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            Id = new Guid("37373737-3737-3737-3737-373737373737"),
                            GroupId = new Guid("19191919-1919-1919-1919-191919191919"),
                            SubjectCode = "",
                            UserId = new Guid("33333333-3333-3333-3333-333333333333")
                        },
                        new
                        {
                            Id = new Guid("38383838-3838-3838-3838-383838383838"),
                            GroupId = new Guid("20202020-2020-2020-2020-202020202020"),
                            SubjectCode = "",
                            UserId = new Guid("11111111-1111-1111-1111-111111111111")
                        });
                });

            modelBuilder.Entity("BookLAB.Domain.Entities.LabImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("FileType")
                        .HasColumnType("integer");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsAvatar")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<int>("LabRoomId")
                        .HasColumnType("integer");

                    b.Property<int>("Size")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LabRoomId")
                        .HasDatabaseName("IX_LabImage_LabRoomId");

                    b.HasIndex("LabRoomId", "IsAvatar")
                        .HasDatabaseName("IX_LabImage_Room_Avatar");

                    b.ToTable("LabImages", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333330"),
                            FileType = 0,
                            ImageUrl = "https://cdn.example/room1.jpg",
                            IsAvatar = true,
                            LabRoomId = 1,
                            Size = 1024
                        },
                        new
                        {
                            Id = new Guid("34343434-3434-3434-3434-343434343434"),
                            FileType = 0,
                            ImageUrl = "https://cdn.example/room2.jpg",
                            IsAvatar = false,
                            LabRoomId = 2,
                            Size = 2048
                        },
                        new
                        {
                            Id = new Guid("35353535-3535-3535-3535-353535353535"),
                            FileType = 0,
                            ImageUrl = "https://cdn.example/room3.jpg",
                            IsAvatar = false,
                            LabRoomId = 3,
                            Size = 512
                        });
                });

            modelBuilder.Entity("BookLAB.Domain.Entities.LabOwner", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("LabRoomId")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("LabRoomId")
                        .HasDatabaseName("IX_LabOwner_LabRoomId");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_LabOwner_UserId");

                    b.HasIndex("UserId", "LabRoomId")
                        .IsUnique()
                        .HasDatabaseName("UQ_LabOwner_User_Room");

                    b.ToTable("LabOwners", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            LabRoomId = 1,
                            UserId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            LabRoomId = 2,
                            UserId = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            LabRoomId = 3,
                            UserId = new Guid("33333333-3333-3333-3333-333333333333")
                        });
                });

            modelBuilder.Entity("BookLAB.Domain.Entities.LabRoom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BuildingId")
                        .HasColumnType("integer");

                    b.Property<int>("Capacity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("HasEquipment")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("OverrideNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("RoomName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("RoomNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BuildingId");

                    b.HasIndex("IsActive");

                    b.HasIndex("BuildingId", "RoomName", "IsDeleted")
                        .IsUnique()
                        .HasDatabaseName("UQ_LabRoom_Building_Name")
                        .HasFilter("\"IsDeleted\" = false");

                    b.ToTable("LabRooms", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BuildingId = 1,
                            Capacity = 0,
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("11111111-1111-1111-1111-111111111111"),
                            Description = "General purpose lab",
                            HasEquipment = true,
                            IsActive = true,
                            IsDeleted = false,
                            Location = "Floor 1",
                            OverrideNumber = 0,
                            RoomName = "Lab A1",
                            RoomNo = "Gamma 101"
                        },
                        new
                        {
                            Id = 2,
                            BuildingId = 1,
                            Capacity = 0,
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("11111111-1111-1111-1111-111111111111"),
                            Description = "Hardware lab",
                            HasEquipment = true,
                            IsActive = true,
                            IsDeleted = false,
                            Location = "Floor 2",
                            OverrideNumber = 0,
                            RoomName = "Lab A2",
                            RoomNo = "Gamma 102"
                        },
                        new
                        {
                            Id = 3,
                            BuildingId = 2,
                            Capacity = 0,
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("11111111-1111-1111-1111-111111111111"),
                            Description = "Software lab",
                            HasEquipment = false,
                            IsActive = true,
                            IsDeleted = false,
                            Location = "Floor 3",
                            OverrideNumber = 0,
                            RoomName = "Lab B1",
                            RoomNo = "Alpha 101"
                        });
                });

            modelBuilder.Entity("BookLAB.Domain.Entities.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<bool>("IsGlobal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset?>("ReadAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId1")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("IsGlobal");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId1");

                    b.ToTable("Notifications", (string)null);
                });

            modelBuilder.Entity("BookLAB.Domain.Entities.PurposeType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("PurposeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("PurposeName")
                        .IsUnique()
                        .HasDatabaseName("UQ_PurposeType_Name");

                    b.ToTable("PurposeTypes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PurposeName = "Lecture"
                        },
                        new
                        {
                            Id = 2,
                            PurposeName = "Practical"
                        },
                        new
                        {
                            Id = 3,
                            PurposeName = "Workshop"
                        });
                });

            modelBuilder.Entity("BookLAB.Domain.Entities.Report", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<bool>("IsResolved")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<int?>("ReportTypeId")
                        .HasColumnType("integer");

                    b.Property<Guid>("ScheduleId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("IsResolved")
                        .HasDatabaseName("IX_Report_Unresolved")
                        .HasFilter("\"IsResolved\" = false");

                    b.HasIndex("ReportTypeId");

                    b.HasIndex("ScheduleId");

                    b.ToTable("Reports", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("21212121-2121-2121-2121-212121212121"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("11111111-1111-1111-1111-111111111111"),
                            Description = "Projector not working",
                            IsResolved = false,
                            ReportTypeId = 1,
                            ScheduleId = new Guid("27272727-2727-2727-2727-272727272727")
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222221"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 1, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("22222222-2222-2222-2222-222222222222"),
                            Description = "Broken chair",
                            IsResolved = false,
                            ReportTypeId = 1,
                            ScheduleId = new Guid("28282828-2828-2828-2828-282828282828")
                        },
                        new
                        {
                            Id = new Guid("23232323-2323-2323-2323-232323232323"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 1, 22, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("33333333-3333-3333-3333-333333333333"),
                            Description = "AC not cooling",
                            IsResolved = false,
                            ReportTypeId = 1,
                            ScheduleId = new Guid("29292929-2929-2929-2929-292929292929")
                        });
                });

            modelBuilder.Entity("BookLAB.Domain.Entities.ReportImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("FileType")
                        .HasColumnType("integer");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("ReportId")
                        .HasColumnType("uuid");

                    b.Property<int>("Size")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ReportId")
                        .HasDatabaseName("IX_ReportImage_ReportId");

                    b.ToTable("ReportImages", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("24242424-2424-2424-2424-242424242424"),
                            FileType = 0,
                            ImageUrl = "https://cdn.example/report1.jpg",
                            ReportId = new Guid("21212121-2121-2121-2121-212121212121"),
                            Size = 1200
                        },
                        new
                        {
                            Id = new Guid("25252525-2525-2525-2525-252525252525"),
                            FileType = 0,
                            ImageUrl = "https://cdn.example/report2.jpg",
                            ReportId = new Guid("22222222-2222-2222-2222-222222222221"),
                            Size = 800
                        },
                        new
                        {
                            Id = new Guid("26262626-2626-2626-2626-262626262626"),
                            FileType = 0,
                            ImageUrl = "https://cdn.example/report3.jpg",
                            ReportId = new Guid("23232323-2323-2323-2323-232323232323"),
                            Size = 600
                        });
                });

            modelBuilder.Entity("BookLAB.Domain.Entities.ReportType", b =>
                {
                    b.Property<int>("ReportTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ReportTypeId"));

                    b.Property<string>("ReportTypeName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("ReportTypeId");

                    b.ToTable("ReportTypes", (string)null);

                    b.HasData(
                        new
                        {
                            ReportTypeId = 1,
                            ReportTypeName = "Thiết bị hư hỏng"
                        },
                        new
                        {
                            ReportTypeId = 2,
                            ReportTypeName = "Thiết bị mất"
                        },
                        new
                        {
                            ReportTypeId = 3,
                            ReportTypeName = "Vấn đề vệ sinh"
                        },
                        new
                        {
                            ReportTypeId = 4,
                            ReportTypeName = "Điều hòa không hoạt động"
                        },
                        new
                        {
                            ReportTypeId = 5,
                            ReportTypeName = "Vấn đề chiếu sáng"
                        },
                        new
                        {
                            ReportTypeId = 6,
                            ReportTypeName = "Bàn ghế hư hỏng"
                        },
                        new
                        {
                            ReportTypeId = 7,
                            ReportTypeName = "Mất kết nối mạng"
                        },
                        new
                        {
                            ReportTypeId = 8,
                            ReportTypeName = "Khóa cửa hỏng"
                        },
                        new
                        {
                            ReportTypeId = 9,
                            ReportTypeName = "Khác"
                        });
                });

            modelBuilder.Entity("BookLAB.Domain.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("RoleName")
                        .IsUnique();

                    b.ToTable("roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            RoleName = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            RoleName = "Manager"
                        },
                        new
                        {
                            Id = 3,
                            RoleName = "Lecturer"
                        });
                });

            modelBuilder.Entity("BookLAB.Domain.Entities.RoomPolicy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<int>("LabRoomId")
                        .HasColumnType("integer");

                    b.Property<string>("PolicyKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PolicyValue")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("PolicyKey");

                    b.HasIndex("LabRoomId", "PolicyKey")
                        .IsUnique()
                        .HasDatabaseName("UQ_Room_PolicyKey");

                    b.ToTable("RoomPolicies", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("30303030-3030-3030-3030-303030303030"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("11111111-1111-1111-1111-111111111111"),
                            IsActive = true,
                            LabRoomId = 1,
                            PolicyKey = "CurfewTime",
                            PolicyValue = "30"
                        },
                        new
                        {
                            Id = new Guid("31313131-3131-3131-3131-313131313131"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("11111111-1111-1111-1111-111111111111"),
                            IsActive = true,
                            LabRoomId = 2,
                            PolicyKey = "CurfewTime",
                            PolicyValue = "Required"
                        },
                        new
                        {
                            Id = new Guid("32323232-3232-3232-3232-323232323232"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("11111111-1111-1111-1111-111111111111"),
                            IsActive = true,
                            LabRoomId = 3,
                            PolicyKey = "CurfewTime",
                            PolicyValue = "No"
                        });
                });

            modelBuilder.Entity("BookLAB.Domain.Entities.Schedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BookingId")
                        .HasColumnType("uuid");

                    b.Property<string>("CalendarEventId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<string>("ImportHash")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<int>("LabRoomId")
                        .HasColumnType("integer");

                    b.Property<Guid>("LecturerId")
                        .HasColumnType("uuid");

                    b.Property<string>("ScheduleStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("ScheduleType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int?>("SlotTypeId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("StudentCount")
                        .HasColumnType("integer");

                    b.Property<string>("SubjectCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BookingId")
                        .IsUnique();

                    b.HasIndex("GroupId");

                    b.HasIndex("ImportHash")
                        .IsUnique();

                    b.HasIndex("LabRoomId");

                    b.HasIndex("LecturerId");

                    b.HasIndex("ScheduleStatus");

                    b.HasIndex("SlotTypeId");

                    b.ToTable("Schedules", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("27272727-2727-2727-2727-272727272727"),
                            BookingId = new Guid("44444444-4444-4444-4444-444444444444"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("11111111-1111-1111-1111-111111111111"),
                            EndTime = new DateTimeOffset(new DateTime(2025, 2, 1, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            GroupId = new Guid("18181818-1818-1818-1818-181818181818"),
                            IsActive = true,
                            IsDeleted = false,
                            LabRoomId = 1,
                            LecturerId = new Guid("11111111-1111-1111-1111-111111111111"),
                            ScheduleStatus = "Active",
                            ScheduleType = "Booking",
                            SlotTypeId = 1,
                            StartTime = new DateTimeOffset(new DateTime(2025, 2, 1, 8, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            StudentCount = 10
                        },
                        new
                        {
                            Id = new Guid("28282828-2828-2828-2828-282828282828"),
                            BookingId = new Guid("55555555-5555-5555-5555-555555555555"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("22222222-2222-2222-2222-222222222222"),
                            EndTime = new DateTimeOffset(new DateTime(2025, 2, 2, 15, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            GroupId = new Guid("19191919-1919-1919-1919-191919191919"),
                            IsActive = true,
                            IsDeleted = false,
                            LabRoomId = 2,
                            LecturerId = new Guid("22222222-2222-2222-2222-222222222222"),
                            ScheduleStatus = "Active",
                            ScheduleType = "Booking",
                            SlotTypeId = 2,
                            StartTime = new DateTimeOffset(new DateTime(2025, 2, 2, 13, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            StudentCount = 20
                        },
                        new
                        {
                            Id = new Guid("29292929-2929-2929-2929-292929292929"),
                            BookingId = new Guid("66666666-6666-6666-6666-666666666666"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("33333333-3333-3333-3333-333333333333"),
                            EndTime = new DateTimeOffset(new DateTime(2025, 2, 3, 10, 30, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            GroupId = new Guid("20202020-2020-2020-2020-202020202020"),
                            IsActive = true,
                            IsDeleted = false,
                            LabRoomId = 3,
                            LecturerId = new Guid("33333333-3333-3333-3333-333333333333"),
                            ScheduleStatus = "Active",
                            ScheduleType = "Academic",
                            SlotTypeId = 3,
                            StartTime = new DateTimeOffset(new DateTime(2025, 2, 3, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            StudentCount = 10
                        });
                });

            modelBuilder.Entity("BookLAB.Domain.Entities.SlotFrame", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<TimeOnly>("EndTimeSlot")
                        .HasColumnType("time without time zone");

                    b.Property<int>("OrderIndex")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("SlotTypeId")
                        .HasColumnType("integer");

                    b.Property<TimeOnly>("StartTimeSlot")
                        .HasColumnType("time without time zone");

                    b.HasKey("Id");

                    b.HasIndex("SlotTypeId");

                    b.HasIndex("SlotTypeId", "OrderIndex")
                        .IsUnique()
                        .HasDatabaseName("UQ_SlotFrame_Type_Order");

                    b.HasIndex("SlotTypeId", "StartTimeSlot")
                        .IsUnique()
                        .HasDatabaseName("UQ_SlotFrame_Type_StartTime");

                    b.ToTable("SlotFrames", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EndTimeSlot = new TimeOnly(9, 30, 0),
                            OrderIndex = 1,
                            SlotTypeId = 1,
                            StartTimeSlot = new TimeOnly(8, 0, 0)
                        },
                        new
                        {
                            Id = 2,
                            EndTimeSlot = new TimeOnly(11, 15, 0),
                            OrderIndex = 2,
                            SlotTypeId = 1,
                            StartTimeSlot = new TimeOnly(9, 45, 0)
                        },
                        new
                        {
                            Id = 3,
                            EndTimeSlot = new TimeOnly(15, 0, 0),
                            OrderIndex = 1,
                            SlotTypeId = 2,
                            StartTimeSlot = new TimeOnly(13, 0, 0)
                        });
                });

            modelBuilder.Entity("BookLAB.Domain.Entities.SlotType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CampusId")
                        .HasColumnType("integer");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("CampusId");

                    b.HasIndex("CampusId", "Code")
                        .IsUnique()
                        .HasDatabaseName("UQ_SlotType_Campus_Code");

                    b.ToTable("SlotTypes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CampusId = 1,
                            Code = "S90",
                            Name = "90-min slot"
                        },
                        new
                        {
                            Id = 2,
                            CampusId = 1,
                            Code = "S120",
                            Name = "120-min slot"
                        },
                        new
                        {
                            Id = 3,
                            CampusId = 2,
                            Code = "S45",
                            Name = "45-min slot"
                        });
                });

            modelBuilder.Entity("BookLAB.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CampusId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Provider")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ProviderId")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("UserCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("UserImageUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.HasKey("Id");

                    b.HasIndex("CampusId");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("UQ_User_Email");

                    b.HasIndex("FullName");

                    b.HasIndex("UserCode")
                        .IsUnique()
                        .HasDatabaseName("UQ_User_Code");

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            CampusId = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "alice@example.edu",
                            FullName = "Alice Tran",
                            IsActive = true,
                            IsDeleted = false,
                            UserCode = "AliceT",
                            UserImageUrl = ""
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            CampusId = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "bob@example.edu",
                            FullName = "Bob Nguyen",
                            IsActive = true,
                            IsDeleted = false,
                            UserCode = "BobN",
                            UserImageUrl = ""
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            CampusId = 2,
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "carol@example.edu",
                            FullName = "Carol Le",
                            IsActive = true,
                            IsDeleted = false,
                            UserCode = "CarolL",
                            UserImageUrl = ""
                        });
                });

            modelBuilder.Entity("BookLAB.Domain.Entities.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("IX_UserRole_RoleId");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_UserRole_UserId");

                    b.ToTable("UserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = new Guid("11111111-1111-1111-1111-111111111111"),
                            RoleId = 1
                        },
                        new
                        {
                            UserId = new Guid("22222222-2222-2222-2222-222222222222"),
                            RoleId = 2
                        },
                        new
                        {
                            UserId = new Guid("33333333-3333-3333-3333-333333333333"),
                            RoleId = 3
                        });
                });

            modelBuilder.Entity("BookLAB.Domain.Entities.Attendance", b =>
                {
                    b.HasOne("BookLAB.Domain.Entities.Schedule", "Schedule")
                        .WithMany()
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookLAB.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Schedule");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BookLAB.Domain.Entities.Booking", b =>
                {
                    b.HasOne("BookLAB.Domain.Entities.LabRoom", "LabRoom")
                        .WithMany()
                        .HasForeignKey("LabRoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BookLAB.Domain.Entities.PurposeType", "PurposeType")
                        .WithMany()
                        .HasForeignKey("PurposeTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BookLAB.Domain.Entities.Schedule", "Schedule")
                        .WithMany()
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BookLAB.Domain.Entities.SlotType", "SlotType")
                        .WithMany()
                        .HasForeignKey("SlotTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("LabRoom");

                    b.Navigation("PurposeType");

                    b.Navigation("Schedule");

                    b.Navigation("SlotType");
                });

            modelBuilder.Entity("BookLAB.Domain.Entities.BookingGroup", b =>
                {
                    b.HasOne("BookLAB.Domain.Entities.Booking", "Booking")
                        .WithMany("BookingGroups")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookLAB.Domain.Entities.Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("BookLAB.Domain.Entities.BookingRequest", b =>
                {
                    b.HasOne("BookLAB.Domain.Entities.Booking", "Booking")
                        .WithMany()
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookLAB.Domain.Entities.User", "Requester")
                        .WithMany()
                        .HasForeignKey("RequestedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BookLAB.Domain.Entities.User", "Reponser")
                        .WithMany()
                        .HasForeignKey("ResponsedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Booking");

                    b.Navigation("Reponser");

                    b.Navigation("Requester");
                });

            modelBuilder.Entity("BookLAB.Domain.Entities.Building", b =>
                {
                    b.HasOne("BookLAB.Domain.Entities.Campus", "Campus")
                        .WithMany("Buildings")
                        .HasForeignKey("CampusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campus");
                });

            modelBuilder.Entity("BookLAB.Domain.Entities.Group", b =>
                {
                    b.HasOne("BookLAB.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BookLAB.Domain.Entities.GroupMember", b =>
                {
                    b.HasOne("BookLAB.Domain.Entities.Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookLAB.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BookLAB.Domain.Entities.LabImage", b =>
                {
                    b.HasOne("BookLAB.Domain.Entities.LabRoom", "LabRoom")
                        .WithMany("LabImages")
                        .HasForeignKey("LabRoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LabRoom");
                });

            modelBuilder.Entity("BookLAB.Domain.Entities.LabOwner", b =>
                {
                    b.HasOne("BookLAB.Domain.Entities.LabRoom", "LabRoom")
                        .WithMany("LabOwners")
                        .HasForeignKey("LabRoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookLAB.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LabRoom");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BookLAB.Domain.Entities.LabRoom", b =>
                {
                    b.HasOne("BookLAB.Domain.Entities.Building", "Building")
                        .WithMany()
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Building");
                });

            modelBuilder.Entity("BookLAB.Domain.Entities.Notification", b =>
                {
                    b.HasOne("BookLAB.Domain.Entities.User", null)
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("BookLAB.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BookLAB.Domain.Entities.Report", b =>
                {
                    b.HasOne("BookLAB.Domain.Entities.ReportType", "ReportType")
                        .WithMany("Reports")
                        .HasForeignKey("ReportTypeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BookLAB.Domain.Entities.Schedule", "Schedule")
                        .WithMany("Reports")
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReportType");

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("BookLAB.Domain.Entities.ReportImage", b =>
                {
                    b.HasOne("BookLAB.Domain.Entities.Report", "Report")
                        .WithMany("ReportImages")
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Report");
                });

            modelBuilder.Entity("BookLAB.Domain.Entities.RoomPolicy", b =>
                {
                    b.HasOne("BookLAB.Domain.Entities.LabRoom", "LabRoom")
                        .WithMany("RoomPolicies")
                        .HasForeignKey("LabRoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LabRoom");
                });

            modelBuilder.Entity("BookLAB.Domain.Entities.Schedule", b =>
                {
                    b.HasOne("BookLAB.Domain.Entities.Booking", "Booking")
                        .WithOne()
                        .HasForeignKey("BookLAB.Domain.Entities.Schedule", "BookingId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BookLAB.Domain.Entities.Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BookLAB.Domain.Entities.LabRoom", "LabRoom")
                        .WithMany()
                        .HasForeignKey("LabRoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BookLAB.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("LecturerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BookLAB.Domain.Entities.SlotType", "SlotType")
                        .WithMany()
                        .HasForeignKey("SlotTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Booking");

                    b.Navigation("Group");

                    b.Navigation("LabRoom");

                    b.Navigation("SlotType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BookLAB.Domain.Entities.SlotFrame", b =>
                {
                    b.HasOne("BookLAB.Domain.Entities.SlotType", "SlotType")
                        .WithMany("SlotFrames")
                        .HasForeignKey("SlotTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SlotType");
                });

            modelBuilder.Entity("BookLAB.Domain.Entities.SlotType", b =>
                {
                    b.HasOne("BookLAB.Domain.Entities.Campus", "Campus")
                        .WithMany()
                        .HasForeignKey("CampusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campus");
                });

            modelBuilder.Entity("BookLAB.Domain.Entities.User", b =>
                {
                    b.HasOne("BookLAB.Domain.Entities.Campus", "Campus")
                        .WithMany()
                        .HasForeignKey("CampusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Campus");
                });

            modelBuilder.Entity("BookLAB.Domain.Entities.UserRole", b =>
                {
                    b.HasOne("BookLAB.Domain.Entities.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookLAB.Domain.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BookLAB.Domain.Entities.Booking", b =>
                {
                    b.Navigation("BookingGroups");
                });

            modelBuilder.Entity("BookLAB.Domain.Entities.Campus", b =>
                {
                    b.Navigation("Buildings");
                });

            modelBuilder.Entity("BookLAB.Domain.Entities.LabRoom", b =>
                {
                    b.Navigation("LabImages");

                    b.Navigation("LabOwners");

                    b.Navigation("RoomPolicies");
                });

            modelBuilder.Entity("BookLAB.Domain.Entities.Report", b =>
                {
                    b.Navigation("ReportImages");
                });

            modelBuilder.Entity("BookLAB.Domain.Entities.ReportType", b =>
                {
                    b.Navigation("Reports");
                });

            modelBuilder.Entity("BookLAB.Domain.Entities.Schedule", b =>
                {
                    b.Navigation("Reports");
                });

            modelBuilder.Entity("BookLAB.Domain.Entities.SlotType", b =>
                {
                    b.Navigation("SlotFrames");
                });

            modelBuilder.Entity("BookLAB.Domain.Entities.User", b =>
                {
                    b.Navigation("Notifications");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
